#!/usr/bin/env python3
"""
Script to combine server parts into a single file.
This is useful for development and testing.
"""

import os
import re

# Define the parts to combine
PARTS = [
    "server_part1.py",
    "server_part2.py",
    "server_part3.py"
]

# Output file
OUTPUT_FILE = "server.py"

def main():
    """Combine server parts into a single file."""
    print(f"Combining server parts into {OUTPUT_FILE}...")
    
    # Check if all parts exist
    for part in PARTS:
        if not os.path.exists(part):
            print(f"Error: {part} does not exist.")
            return
    
    # Read all parts
    contents = []
    imports = set()
    
    for part in PARTS:
        with open(part, "r", encoding="utf-8") as f:
            content = f.read()
            
            # Extract imports
            import_lines = re.findall(r'^import .*$|^from .* import .*$', content, re.MULTILINE)
            for imp in import_lines:
                imports.add(imp)
            
            # Remove imports from content
            content = re.sub(r'^import .*$|^from .* import .*$', '', content, flags=re.MULTILINE)
            
            # Add to contents
            contents.append(content.strip())
    
    # Write combined file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        # Write header
        f.write('#!/usr/bin/env python3\n')
        f.write('"""\n')
        f.write('Realtime Voice Chat Server\n')
        f.write('This file is automatically generated from server_part*.py files.\n')
        f.write('Do not edit this file directly.\n')
        f.write('"""\n\n')
        
        # Write imports
        f.write('# Imports\n')
        for imp in sorted(imports):
            f.write(f'{imp}\n')
        f.write('\n')
        
        # Write contents
        for i, content in enumerate(contents):
            f.write(f'# Part {i+1}: {PARTS[i]}\n')
            f.write(content)
            f.write('\n\n')
        
        # Write main block
        f.write('if __name__ == "__main__":\n')
        f.write('    main()\n')
    
    print(f"Successfully combined {len(PARTS)} parts into {OUTPUT_FILE}.")

if __name__ == "__main__":
    main()
